version: 0.2
phases:
 install:
  runtime-versions:
   java: openjdk8
 pre_build:
  commands:
   - echo gradle -version
 build:
  commands:
   - gradle buildZip
   - aws cloudformation package --debug --template-file samTemplate.yaml --s3-bucket boneylambdabucket/lambdaTest --output-template-file outputSamTemplate.yaml
 post_build:
  commands:
   - echo gradle -version
artifacts:
 type: zip
 files:
   - samTemplate.yaml
   - outputSamTemplate.yaml
