version: 0.2
phases:
 install:
  runtime-versions:
   java: openjdk8
 pre_build:
  commands:
   - echo gradle -version
   - sudo apt-get update
   - sudo apt upgrade gradle
 build:
  commands:
   - gradle buildZip
   - aws cloudformation package --template-file samTemplate.yaml --s3-bucket boneylambda --s3-prefix function --output-template-file outputtemplate.yaml
 post_build:
  commands:
   - echo gradle -version
artifacts:
 type: zip
 files:
   - samTemplate.yaml
   - outputtemplate.yaml
