version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket boneylambdabucket --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
