version: 0.2
phases:
 pre_build:
  commands:
   - echo gradle -version
 build:
  commands:
   - gradle buildZip
 post_build:
  commands:
   - aws lambda update-function-code --function-name lambda-test --zip-file fileb://build/distributions//lambdaTest-0.0.1.zip
