AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Demo Lambda
Resources:
  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.lambda.lambdaTest.MainController::test
      Runtime: java8
      CodeUri: build/distributions/lambdaTest-0.0.1.zip
      Role: arn:aws:iam::435341406651:role/CloudFormationServiceRole
      FunctionName: lambda-test
      Description: 'Lambda function for Demo'
      MemorySize: 128
      Timeout: 30
